import { scanJson } from "./scanner.js";
import { verifyJson } from "./verifier.js";
import type { JsonValue, ReportOptions, ScanResult } from "./types.js";

const plural = (count: number, noun: string): string => `${count} ${noun}${count === 1 ? "" : "s"}`;
const countForReport = (count: number, cmsReport: boolean | undefined): string =>
  cmsReport && count >= 1 && count <= 10 ? "<11" : String(count);
const pluralForReport = (count: number, noun: string, cmsReport: boolean | undefined): string =>
  cmsReport && count >= 1 && count <= 10 ? `<11 ${noun}s` : plural(count, noun);
const csvEscape = (value: string | number | undefined): string => {
  const text = String(value ?? "");
  if (/[",\n\r]/.test(text)) {
    return `"${text.replaceAll('"', '""')}"`;
  }
  return text;
};

export function renderScanText(result: ScanResult): string {
  if (result.findings.length === 0) {
    return "No likely PHI/PII findings detected.";
  }

  return result.findings
    .map((finding) => `${finding.severity.toUpperCase()} ${finding.path} ${finding.ruleId} ${finding.label}`)
    .join("\n");
}

export function renderMarkdownReport(json: JsonValue, file = "input", options: ReportOptions = {}): string {
  const scan = scanJson(json, file, options);
  const verification = verifyJson(json, options);
  const lines: string[] = [
    "# PHI/PII De-identification Report",
    "",
    `- File: \`${file}\``,
    `- Mode: ${options.mode ?? "default"}`,
    `- Status: ${verification.passed ? "PASS" : "WARNINGS REMAIN"}`,
    `- Findings: ${pluralForReport(scan.findings.length, "rule hit", options.cmsReport)}`,
    `- Remaining warnings: ${pluralForReport(verification.findings.length, "finding", options.cmsReport)}`,
    "",
    "## Privacy Limits",
    "",
    "This report is generated by deterministic local rules. It is a share-safe helper for healthcare debugging artifacts, not a certified HIPAA de-identification determination.",
    ...(options.cmsReport
      ? [
          "",
          "CMS-style report mode is enabled. Aggregate counts from 1 to 10 are suppressed in report summaries as <11; this does not perform full CMS output review."
        ]
      : []),
    "",
    "## Rule Counts",
    ""
  ];

  if (scan.ruleSummaries.length === 0) {
    lines.push("- None");
  } else {
    for (const summary of scan.ruleSummaries) {
      lines.push(`- ${summary.ruleId}: ${countForReport(summary.count, options.cmsReport)} (${summary.label})`);
    }
  }

  lines.push("", "## Findings", "");

  if (scan.findings.length === 0) {
    lines.push("- No likely PHI/PII findings detected.");
  } else {
    for (const finding of scan.findings) {
      lines.push(`- ${finding.severity.toUpperCase()} \`${finding.path}\` ${finding.ruleId}: ${finding.reason}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export function renderCsvReport(json: JsonValue, file = "input", options: ReportOptions = {}): string {
  const scan = scanJson(json, file, options);
  const rows = [
    ["file", "path", "severity", "rule_id", "label", "placeholder", "reason", "value_preview"],
    ...scan.findings.map((finding) => [
      file,
      finding.path,
      finding.severity,
      finding.ruleId,
      finding.label,
      finding.placeholder,
      finding.reason,
      finding.valuePreview ?? ""
    ])
  ];

  return `${rows.map((row) => row.map(csvEscape).join(",")).join("\n")}\n`;
}
